<?php
$type_mapping = array(
	'bit' => 'int1',
	'tinyint' => 'int1',
	'bool' => 'bool',
	'boolean' => 'bool',
	'smallint' => 'int2',
	'mediumint' => 'int3',
	'int' => 'int4',
	'integer' => 'int4',
	'bigint' => 'int8',
	'float' => 'float',
	'double' => 'double',
	'doubleprecision' => 'double',
	'float unsigned' => 'float',
	'decimal' => 'dec',
	'dec' => 'dec',

	'date' => 'date',
	'datetime' => 'datetime',
	'timestamp' => 'timestamp',
	'time' => 'time',
	'year' => 'int2',
	'char' => 'char',
	'nchar' => 'char',
	'varchar' => 'varchar',
	'nvarchar' => 'varchar',
	'binary' => 'binary',
	'varbinary' => 'varbinary',
	'tinyblob' => 'blob',
	'tinytext' => 'text',
	'blob' => 'blob',
	'text' => 'text',
	'mediumblob' => 'blob',
	'mediumtext' => 'text',
	'longblob' => 'blob',
	'longtext' => 'text',
	'enum' => 'enum',
	'set' => 'set',
);

$fields = array(
	'id' => 'int',
	'type' => 'tiny int',
	'comment' => 'varchar',
);